apiVersion: v1
kind: Namespace
metadata:
  name: cluster-named-dns
  labels:
    name: cluster-named-dns
    entity: cluster
    env: named
    capability: dns
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/audit: privileged
    pod-security.kubernetes.io/warn: privileged
